import Head from 'next/head';

export interface PageProps {
  title: string;
  description?: string;
}

const Page: React.FC<PageProps> = ({ children, title, description }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        {description && (
          <meta name="description" content="Generated by create next app" />
        )}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  );
};

export default Page;
